const engineeringBooks = [
    {
        title: CHM 101 1st and 2nd order reaction',
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
semester: "1st semester",
    },
    {
        title: 'CHM101 STARLINK',
        author: 'Dr Honor',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space1.avif',
        fileType: 'pdf',
    },
    {
        title: 'CHM101 STARLINK 3.0',
        author: 'Prof Adebayo',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space2.avif',
        fileType: 'epub',
    },
    {
        title: 'CHM101 STARLINK JESUS adhgxcbwfegcgflchifgbh',
        author: 'Prof Adebayo',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space3.avif',
        fileType: 'pdf',
    },
    {
        title: 'CHM101 STARLINK 3.0',
        author: 'Prof Adebayo',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space2.avif',
        fileType: 'epub',
    },
    {
        title: 'CHM101 STARLINK JESUS kjhfchjkcafhjkascfhbaschbvfhbfsgvhbsafgvbhkvafbhkafgvbhdfgbadfvbvbh',
        author: 'Prof Adebayo',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space3.avif',
        fileType: 'pdf',
    },
    {
        title: 'CHM101 STARLINK 3.0',
        author: 'Prof Adebayo',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space2.avif',
        fileType: 'epub',
    },
    {
        title: 'CHM101 STARLINK JESUS',
        author: 'Prof Adebayo',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space3.avif',
        fileType: 'pdf',
    },
    {
        title: 'CHM101 STARLINK 3.0',
        author: 'Prof Adebayo',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space2.avif',
        fileType: 'epub',
    },
    {
        title: 'CHM101 STARLINK JESUS',
        author: 'Prof Adebayo',
        keywords: ['chm101', '101', 'chemistry'],
        downLink: '/assets/images/space3.avif',
        fileType: 'pdf',
    },
];