const engineeringBooks = [
    {
        title: "CHM 101 1st and 2nd order reaction",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 102', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101: ATOMS & MOLECULES",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101 Relativity by Einstein",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102: Modular Arithemetic",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101: SEPERATION TECHNIQUES",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101: TIME TRAVEL",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102: GAME THEORY",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101 1st and 2nd order reaction",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101: ATOMS & MOLECULES",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101 Relativity by Einstein",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102: Modular Arithemetic",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101: SEPERATION TECHNIQUES",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101: TIME TRAVEL",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102: GAME THEORY",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101 1st and 2nd order reaction",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101: ATOMS & MOLECULES",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101 Relativity by Einstein",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102: Modular Arithemetic",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101: SEPERATION TECHNIQUES",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101: TIME TRAVEL",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102: GAME THEORY",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101 1st and 2nd order reaction",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101: ATOMS & MOLECULES",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction','chemistry'],
        semester: "1st semester",
    },
    {
        title: "PHY 101 Relativity by Einstein jchwcg ghFGC FQ FKJQBV HJBC HJQC JHFB JHV",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102: Modular Arithemetic",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
    {
        title: "CHM 101: SEPERATION TECHNIQUES",
        courseCode: "CHM 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['chm','101','chm 101', 'chm101','order','reaction'],
        semester: "1st semester",
    },
    {
        title: "PHY 101: TIME TRAVEL",
        courseCode: "PHY 101",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['phy','phy101','phy 101', 'physics',],
        semester: "1st semester",
    },
    {
        title: "MTH 102: GAME THEORY",
        courseCode: "MTH 102",
        author: "",
        ratings: "4.5",
        downLink: "https://drive.google.com/uc?export=download&id=1Qbr7j2cUDR_03XAthhvTa8F4be1YAgnj",
        keywords: ['mth','mth102','mth 101', 'mathematics',],
        semester: "1st semester",
    },
]